class_Infor :
    num_age       : 6
    num_emo       : 7   
    num_skin      : 4
    num_mask      : 2
    num_gender    : 2
    num_race      : 3   
    
     
data: 
    img_folder:  '/root/code/exp/faceany/data/'
    train_anno:  '/root/code/exp/faceany/label/train_data.csv'
    val_anno: '/root/code/exp/faceany/label/val_data.csv'

model:
    backbone_type: 'timm'
    model_name: 'convnextv2_base.fcmae_ft_in22k_in1k'
    